apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blocker-slack
  name: blocker-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocker-slack
  template:
    metadata:
      labels:
        app: blocker-slack
    spec:
      containers:
      - image: quay.io/eparis/blocker-slack:latest
        imagePullPolicy: Always
        name: blocker-slack
        resources: {}
        volumeMounts:
        - name: slack-key
          readOnly: true
          mountPath: /etc/slack
        - name: bugzilla-api-key
          readOnly: true
          mountPath: /etc/bugzilla
        - name: blocker-slack-config
          readOnly: true
          mountPath: /etc/blocker-slack
      restartPolicy: Always
      volumes:
      - name: bugzilla-api-key
        secret:
          secretName: bugzilla-api-key
          defaultMode: 420
      - name: slack-key
        secret:
          secretName: slack-key
          defaultMode: 420
      - name: blocker-slack-config
        configMap:
          name: blocker-slack-config
          defaultMode: 420
