kind: Job
apiVersion: batch/v1
metadata:
  name: upcoming-sprint-stats
  namespace: ocp-eng-architects
  labels:
    app: upcoming-sprint-stats
    type: oneshot
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: upcoming-sprint-stats
    spec:
      volumes:
        - name: bugzilla-api-key
          secret:
            secretName: bugzilla-api-key
            defaultMode: 420
      containers:
        - name: upcoming-sprint-stats
          image: 'quay.io/eparis/upcoming-sprint-stats:latest'
          resources: {}
          volumeMounts:
            - name: bugzilla-api-key
              readOnly: true
              mountPath: /etc/bugzilla
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
